//
// Created by Thales Nunes on 6/6/22.
//

#ifndef MODULO1_TIPOSERVICO_H
#define MODULO1_TIPOSERVICO_H
enum class TipoServico {
    MEDICAO, INADIMPLENCIA, ENCERRAMENTO, LIGACAO_NOVA, RELIGACAO_POR_PAGAMENTO, TROCA_MEDIDOR
};

#endif //MODULO1_TIPOSERVICO_H
